[package]
name = "repo-cli"
version = "0.1.2"
authors = ["James Simpson <edenofest@gmail.com>"]
edition = "2018"
include = ["src/**/**", "Cargo.toml", "Cargo.lock", "readme.md"]
description = "A sane way to manage all of your git repositories"
repository = "https://github.com/edeneast/repo.git"
documentation = "https://github.com/edeneast/repo.git"
homepage = "https://github.com/edeneast/repo.git"
keywords = [
    'automation',
    'cli',
    'developer-tools',
    'git',
    'productivity',
]
license = "Apache-2.0"
readme = "readme.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# Vendor OpenSSL, use this if you have trouble cross-compiling starship
tls-vendored = ["native-tls/vendored"]

[dependencies]
anyhow = "^1.0.29"
better-panic = "^0.2.0"
clap = "^2.33.1"
dialoguer = "^0.6.2"
dirs = "^2.0.2"
git2 = "^0.13.5"
git2_credentials = "^0.6.0"
glob = "^0.3.0"
lazy_static = "^1.4.0"
log = "^0.4.8"
pretty_env_logger = "^0.4.0"
regex = "^1.3.6"
ron = "~0.5.1"
serde = { version = "~1.0.110", features = ["derive"] }
serde_json = "~1.0.53"
shellexpand = "^2.0.0"
toml = "^0.5.6"
url = { version = "^2.1.1", features = ["serde"] }

# optional
native-tls = { version = "0.2", optional = true }

[[bin]]
name = "repo"
path = "./src/bin/repo/main.rs"
