[package]
name = "repo"
version = "0.1.0"
authors = ["James Simpson <edenofest@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2.33.0"
anyhow = "^1.0.27"

[[bin]]
name = "repo"
path = "./src/bin/repo/main.rs"
