[package]
name = "repo"
version = "0.1.0"
authors = ["James Simpson <james.simpson9339@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2.33.0"
anyhow = "^1.0.27"
url = "^2.1.1"
regex = "^1.3.5"
shellexpand = "^2.0.0"
lazy_static = "^1.4.0"
dirs = "^2.0.2"
toml = "^0.5.6"
serde = { version = "^1.0.105", features = ["derive"] }

[[bin]]
name = "repo"
path = "./src/bin/repo/main.rs"
