[package]
name = "repo"
version = "0.1.0"
authors = ["James Simpson <james.simpson9339@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2.33.0"
anyhow = "^1.0.28"
url = { version = "^2.1.1", features = ["serde"] }
regex = "^1.3.6"
shellexpand = "^2.0.0"
lazy_static = "^1.4.0"
dirs = "^2.0.2"
toml = "^0.5.6"
serde = { version = "^1.0.105", features = ["derive"] }
glob = "^0.3.0"
log = "^0.4.8"
pretty_env_logger = "^0.4.0"
better-panic = "^0.2.0"

[[bin]]
name = "repo"
path = "./src/bin/repo/main.rs"
