[package]
name = "repo"
version = "0.1.0"
authors = ["James Simpson <edenofest@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0.28"
better-panic = "^0.2.0"
clap = "^2.33.0"
dialoguer = "^0.5.0"
dirs = "^2.0.2"
git2 = "^0.13.1"
git2_credentials = "^0.6.0"
glob = "^0.3.0"
lazy_static = "^1.4.0"
log = "^0.4.8"
pretty_env_logger = "^0.4.0"
regex = "^1.3.6"
serde = { version = "^1.0.106", features = ["derive"] }
shellexpand = "^2.0.0"
toml = "^0.5.6"
url = { version = "^2.1.1", features = ["serde"] }

[[bin]]
name = "repo"
path = "./src/bin/repo/main.rs"
